// This file is auto-generated. DO NOT EDIT BY HAND
// Use generate_data.py to rebuild this file if needed

// https://doc.qt.io/qt-5/qtqml-javascript-resources.html
.pragma library

var currencies = {
	"1INCH": {"code": "1INCH", "name": "1inch", },
	"ADA": {"code": "ADA", "name": "Cardano", },
	"ATOM": {"code": "ATOM", "name": "Cosmos", },
	"BCH": {"code": "BCH", "name": "Bitcoin Cash", "symbol": "฿", },
	"BNB": {"code": "BNB", "name": "Binance Coin", },
	"BNT": {"code": "BNT", "name": "Bancor", },
	"BSV": {"code": "BSV", "name": "Bitcoin SV", },
	"BTC": {"code": "BTC", "name": "Bitcoin", "symbol": "₿", },
	"BTG": {"code": "BTG", "name": "Bitcoin Gold", },
	"BTT": {"code": "BTT", "name": "BitTorrent", },
	"BUSD": {"code": "BUSD", "name": "Binance USD", "symbol": "B$", },
	"COMP": {"code": "COMP", "name": "Compound", },
	"CZK": {"code": "CZK", "name": "Czech Koruna", "symbol": "Kč", },
	"DASH": {"code": "DASH", "name": "Dash", },
	"DOGE": {"code": "DOGE", "name": "Dogecoin", },
	"DOT": {"code": "DOT", "name": "Polkadot", },
	"EOS": {"code": "EOS", },
	"ETC": {"code": "ETC", "name": "Ethereum Classic", },
	"ETH": {"code": "ETH", "name": "Ethereum", "symbol": "Ξ", },
	"EUR": {"code": "EUR", "name": "Euro", "symbol": "€", },
	"FIL": {"code": "FIL", "name": "Filecoin", },
	"GAME": {"code": "GAME", "name": "GameCredits", },
	"GBP": {"code": "GBP", "name": "British Pound", "symbol": "£", },
	"GLM": {"code": "GLM", "name": "Golem", },
	"JPY": {"code": "JPY", "name": "Japanese Yen", "symbol": "¥", },
	"LINK": {"code": "LINK", "name": "Chainlink", },
	"LSK": {"code": "LSK", "name": "Lisk", },
	"LTC": {"code": "LTC", "name": "Litecoin", "symbol": "Ł", },
	"LUNA": {"code": "LUNA", "name": "Terra", },
	"MKR": {"code": "MKR", "name": "Maker", },
	"PLN": {"code": "PLN", "name": "Polish Zloty", "symbol": "zł", },
	"SOL": {"code": "SOL", "name": "Solana", },
	"THETA": {"code": "THETA", "name": "Theta", },
	"UNI": {"code": "UNI", "name": "Uniswap", },
	"USD": {"code": "USD", "name": "US Dollar", "symbol": "$", },
	"USDC": {"code": "USDC", "name": "USD Coin", "symbol": "$C", },
	"USDT": {"code": "USDT", "name": "USD Tether", "symbol": "$T", },
	"WBTC": {"code": "WBTC", "name": "Wrapped Bitcoin", },
	"XLM": {"code": "XLM", "name": "Stellar", },
	"XMR": {"code": "XMR", "name": "Monero", },
	"XRP": {"code": "XRP", "name": "Ripple", "symbol": "Ʀ", },
	"XTZ": {"code": "XTZ", "name": "Tezos", },
	"ZEC": {"code": "ZEC", "name": "ZCash", },
	"ZRX": {"code": "ZRX", "name": "0x", },
}
var exchanges = {
	"binance-com": {
		"name": "Binance",
		"url": "https://binance.com/",
		"getUrl": function(crypto, pair) {
			return `https://api1.binance.com/api/v3/ticker/price?symbol=${crypto}${pair}`
		},
		"getRateFromExchangeData": function(data, crypto, pair) {
			return data.price
		},
		"pairs": {
			"1INCH": ["BTC","BUSD","USDC","USDT",],
			"ADA": ["BNB","BTC","BUSD","ETH","EUR","GBP","JPY","USDC","USDT",],
			"ATOM": ["BNB","BTC","BUSD","ETH","EUR","USDC","USDT",],
			"BCH": ["BNB","BTC","BUSD","EUR","JPY","USDC","USDT",],
			"BNB": ["BTC","BUSD","ETH","EUR","GBP","JPY","USD","USDC","USDT",],
			"BNT": ["BTC","BUSD","ETH","USDT",],
			"BTC": ["BUSD","EUR","GBP","JPY","PLN","USD","USDC","USDT",],
			"BTG": ["BTC","BUSD","ETH","USDT",],
			"BTT": ["BNB","BTC","BUSD","EUR","USDC","USDT",],
			"BUSD": ["PLN","USDT",],
			"COMP": ["BNB","BTC","BUSD","USDC","USDT",],
			"DASH": ["BNB","BTC","BUSD","ETH","USDC","USDT",],
			"DOGE": ["BNB","BTC","BUSD","EUR","GBP","JPY","USDC","USDT",],
			"DOT": ["BNB","BTC","BUSD","ETH","EUR","GBP","USDC","USDT",],
			"EOS": ["BNB","BTC","BUSD","ETH","EUR","USDC","USDT",],
			"ETC": ["BNB","BTC","BUSD","ETH","EUR","GBP","USDC","USDT",],
			"ETH": ["BTC","BUSD","EUR","GBP","JPY","PLN","USD","USDC","USDT",],
			"EUR": ["BUSD","USDC","USDT",],
			"FIL": ["BNB","BTC","BUSD","ETH","USDC","USDT",],
			"GBP": ["BUSD","USDT",],
			"GLM": ["BTC","BUSD","ETH","USDT",],
			"LINK": ["BNB","BTC","BUSD","ETH","EUR","GBP","JPY","USDC","USDT",],
			"LSK": ["BNB","BTC","BUSD","ETH","USDC","USDT",],
			"LTC": ["BNB","BTC","BUSD","ETH","EUR","GBP","JPY","USDC","USDT",],
			"LUNA": ["BNB","BTC","BUSD","ETH","EUR","GBP","USDC","USDT",],
			"MKR": ["BNB","BTC","BUSD","USDC","USDT",],
			"SOL": ["BNB","BTC","BUSD","ETH","EUR","GBP","JPY","USD","USDC","USDT",],
			"THETA": ["BNB","BTC","BUSD","ETH","EUR","USDC","USDT",],
			"UNI": ["BNB","BTC","BUSD","ETH","EUR","USDC","USDT",],
			"USDC": ["BNB","BUSD","CZK","PLN","USD","USDT",],
			"USDT": ["CZK","PLN","USD",],
			"WBTC": ["BTC","BUSD","ETH","USDT",],
			"XLM": ["BNB","BTC","BUSD","ETH","EUR","JPY","USDC","USDT",],
			"XMR": ["BNB","BTC","BUSD","ETH","USDT",],
			"XRP": ["BNB","BTC","BUSD","ETH","EUR","GBP","JPY","USDC","USDT",],
			"XTZ": ["BNB","BTC","BUSD","ETH","USDC","USDT",],
			"ZEC": ["BNB","BTC","BUSD","ETH","USDC","USDT",],
			"ZRX": ["BNB","BTC","BUSD","ETH","USDT",],
		},
	},
	"bitstamp-net": {
		"name": "Bitstamp",
		"url": "https://bitstamp.net/",
		"getUrl": function(crypto, pair) {
			return `https://www.bitstamp.net/api/v2/ticker/${crypto.toLowerCase()}${pair.toLowerCase()}`
		},
		"getRateFromExchangeData": function(data, crypto, pair) {
			return data.ask
		},
		"pairs": {
			"BCH": ["BTC","EUR","GBP","USD",],
			"BTC": ["EUR","GBP","USD","USDC",],
			"ETH": ["BTC","EUR","GBP","USD","USDC",],
			"EUR": ["USD",],
			"GBP": ["EUR","USD",],
			"LINK": ["BTC","ETH","EUR","GBP","USD",],
			"LTC": ["BTC","EUR","GBP","USD",],
			"MKR": ["BTC","EUR","USD",],
			"UNI": ["BTC","EUR","USD",],
			"USDC": ["EUR","USD",],
			"XLM": ["BTC","EUR","GBP","USD",],
			"XRP": ["BTC","EUR","GBP","USD",],
			"ZRX": ["BTC","EUR","USD",],
		},
	},
	"coinmate-io": {
		"name": "Coinmate",
		"url": "https://coinmate.io/",
		"getUrl": function(crypto, pair) {
			return `https://coinmate.io/api/ticker?currencyPair=${crypto}_${pair}`
		},
		"getRateFromExchangeData": function(data, crypto, pair) {
			return data.data.ask
		},
		"pairs": {
			"ADA": ["CZK","EUR",],
			"BTC": ["CZK","EUR",],
			"ETH": ["BTC","CZK","EUR",],
			"LTC": ["CZK","EUR",],
			"SOL": ["CZK","EUR",],
			"USDC": ["CZK","EUR",],
			"XRP": ["CZK","EUR",],
		},
	},
	"kraken-com": {
		"name": "Kraken",
		"url": "https://kraken.com/",
		"getUrl": function(crypto, pair) {
			return `https://api.kraken.com/0/public/Ticker?pair=${crypto}${pair}`
		},
		"getRateFromExchangeData": function(data, crypto, pair) {
			return data.result[Object.keys(data['result'])[0]].a[0]
		},
		"pairs": {
			"1INCH": ["EUR","USD",],
			"ADA": ["BTC","ETH","EUR","GBP","USD","USDC","USDT",],
			"ATOM": ["BTC","ETH","EUR","GBP","USD","USDC","USDT",],
			"BCH": ["BTC","ETH","EUR","GBP","JPY","USD","USDC","USDT",],
			"BNB": ["EUR","USD","USDC","USDT",],
			"BNT": ["EUR","USD",],
			"BTC": ["EUR","GBP","JPY","USD","USDC","USDT",],
			"BTT": ["EUR","USD",],
			"COMP": ["BTC","EUR","USD",],
			"DASH": ["EUR","USD",],
			"DOGE": ["BTC","EUR","GBP","USD","USDC","USDT",],
			"DOT": ["BTC","ETH","EUR","GBP","JPY","USD","USDC","USDT",],
			"ETC": ["BTC","ETH","EUR","USD",],
			"ETH": ["BTC","EUR","GBP","JPY","USD","USDC","USDT",],
			"EUR": ["GBP","JPY","USD",],
			"FIL": ["BTC","ETH","EUR","GBP","USD",],
			"GBP": ["USD",],
			"LINK": ["BTC","ETH","EUR","GBP","JPY","USD","USDC","USDT",],
			"LSK": ["EUR","USD",],
			"LTC": ["BTC","ETH","EUR","GBP","JPY","USD","USDC","USDT",],
			"LUNA": ["EUR","USD",],
			"SOL": ["BTC","ETH","EUR","GBP","USD","USDC","USDT",],
			"UNI": ["BTC","ETH","EUR","USD",],
			"USD": ["JPY",],
			"USDC": ["EUR","GBP","USD","USDT",],
			"USDT": ["EUR","GBP","JPY","USD",],
			"WBTC": ["BTC","EUR","USD",],
			"XLM": ["BTC","EUR","GBP","USD",],
			"XMR": ["BTC","EUR","USD","USDC","USDT",],
			"XRP": ["BTC","ETH","EUR","GBP","USD","USDC","USDT",],
			"XTZ": ["EUR","USD","USDC","USDT",],
			"ZEC": ["EUR","USD",],
			"ZRX": ["BTC","EUR","USD",],
		},
	},
}
